build: false

environment:
  matrix:
    - PYTHON: 2.7
      PKG: pip
    - PYTHON: 2.7
      PKG: conda
    - PYTHON: 3.5
      PKG: pip
    - PYTHON: 3.5
      PKG: conda
    - PYTHON: 3.6
      PKG: pip
    - PYTHON: 3.6
      PKG: conda
    - PYTHON: 3.7
      PKG: pip
    - PYTHON: 3.7
      PKG: conda

init:
  - "ECHO %PYTHON% %PKG%"

before_install:
  - "set PATH=C:\\Miniconda3;C:\\Miniconda3\\Scripts;%PATH%"
  - conda update conda --yes --quiet
  - "conda create --name test-env python=%PYTHON% pytest pip --yes --quiet"
  - activate test-env

install:
  - ps: |
      if ($env:PKG -eq "pip")
      {
        pip install tables -qqq  # qq to suppress python 2.7 deprecation error
        pip list
      }
  - ps: |
      if ($env:PKG -eq "conda")
      {
        conda install pytables --channel conda-forge --yes --quiet
        conda list
      }

test_script:
  - py.test
