build: false

environment:
  matrix:
    - PYTHON: 2.7
      PKG: pip
      MINICONDA: C:\Miniconda
    - PYTHON: 2.7
      PKG: conda
      MINICONDA: C:\Miniconda
    - PYTHON: 3.6
      PKG: pip
      MINICONDA: C:\Miniconda3
    - PYTHON: 3.6
      PKG: conda
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON% %PKG%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda update conda --quiet
  - "conda create --name test-env python=%PYTHON% pytest --yes --quiet"
  - activate test-env
  - ps: |
      if ($env:PKG -eq "pip")
      {
        pip install tables
        pip list
      }
  - ps: |
      if ($env:PKG -eq "conda")
      {
        conda install pytables --channel conda-forge --yes --quiet
        conda list
      }

test_script:
  - py.test
